eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8860/eureka/
server:
  tomcat:
    max-connections: 0 # 默认值
    max-threads: 0 # 默认值
  port: 8863
spring:
  application:
    name: service-feign
  resources:
      static-locations: classpath:/templates
  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 10240Mb
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
    history-level: full
  #redis:
    #shiro:
      #host: 127.0.0.1
      #port: 6379
      #timeout: 0
      #password: 142857
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
hystrix:
  threadpool:
    default:
      coreSize: 500

