server:
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  port: 8864
spring:
  application:
    name: eureka-client-apiservice
  #datasource
  datasource:
    url : jdbc:mysql://172.16.107.205:3306/shiro?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
  jpa:
    database : MYSQL
    # Show or not log for each sql query
    show-sql : true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto : update
      # Naming strategy
      #[org.hibernate.cfg.ImprovedNamingStrategy | org.hibernate.cfg.DefaultNamingStrategy]
      naming-strategy : org.hibernate.cfg.DefaultNamingStrategy
  # stripped before adding them to the entity manager)
  properties:
    hibernate:
      dialect : org.hibernate.dialect.MySQL5Dialect
      exclude: WEB-INF/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8860/eureka/
logging.config:
  classpath: log4j2.xml
logging.level.org.springframework: info